# -*- coding: utf-8 -*-
"""Day2Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12WqZXvfSOeKJVRrOm2aXVo858_ioGfFp
"""

"""
Basics Demo....
"""
a=10
b=10
c=257
d=257
name="pooja"
#operators
print(a>b)
print(a>=b)
print(a!=b)

print(f"Addition is :: {a+b} \nSubstraction is :: {a-b} \nMultipliction is:: {a*b} \
\nDivision is :: {a/b} \nFloor Division :: {a//b}")

print(id(a))  
print(id(b))   #same address of a and b
print(id(c))    #not same address for c and d ..bcoz in range of -5 to 256 address is same
id(d)

print(a>b or a<c)
print(a>b and a<c)

print('a' in name)
print('a' not in name)



